services:
  - type: web
    name: eld-trip-planner-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL
        value: "1"
      - key: PYTHON_VERSION
        value: "3.12.3"
