# Generated by Django 6.1.1 on 2026-10-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_used_hours', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('total_miles', models.FloatField(default=0)),
                ('total_days', models.IntegerField(default=0)),
                ('result', models.JSONField(default=dict)),
            ],
        ),
    ]
